name: "WK7 Bot"
description: "Discord Bot for Home Assistant integration and RSS feed management."
version: "1.0.16"
slug: "wk7bot"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
map:
  - config:rw
  - ssl
options:
  discord_token: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
schema:
  discord_token: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str?
  mqtt_password: str?
hassio_api: true
homeassistant_api: true
hassio_role: "default"