<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <UserSecretsId>8c7b6003-f1eb-4482-b254-5ac26a348c0c</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CodeHollow.FeedReader" Version="1.2.6" />
        <PackageReference Include="Discord.Net" Version="3.17.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>